services:
  app:
    build: .
    container_name: flask_app
    ports:
      - "5000:5000"
    depends_on:
      - db
      - redis
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/flask_db
      - REDIS_URL=redis://redis:6379/0
    volumes:
      - .:/app

  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: flask_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    container_name: redis_cache
    ports:
      - "6379:6379"